In [2]:
import pandas as pd

dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder

dataset['sex'] = LabelEncoder().fit_transform(dataset['sex'])
dataset['smoker'] = LabelEncoder().fit_transform(dataset['smoker'])

dataset

      age  sex     bmi  children  smoker      charges
0      19    0  27.900         0       1  16884.92400
1      18    1  33.770         1       0   1725.55230
2      28    1  33.000         3       0   4449.46200
3      33    1  22.705         0       0  21984.47061
4      32    1  28.880         0       0   3866.85520
...   ...  ...     ...       ...     ...          ...
1333   50    1  30.970         3       0  10600.54830
1334   18    0  31.920         0       0   2205.98080
1335   18    0  36.850         0       0   1629.83350
1336   21    0  25.800         0       0   2007.94500
1337   61    0  29.070         0       1  29141.36030

[1338 rows x 6 columns]

In [4]:
independent = dataset[['age', 'sex', 'bmi', 'children', 'smoker']]
dependent = dataset[['charges']]

In [5]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(independent, dependent, test_size=0.3, random_state=0)

In [87]:
from sklearn.svm import SVR #importing the Linear regression library from sklearn
from sklearn.preprocessing import StandardScaler

# regressor = SVR(kernel="linear", C=0.1)
# regressor = SVR(kernel="linear", C=1)
# regressor = SVR(kernel="linear", C=10)
# regressor = SVR(kernel="linear", C=100)
# regressor = SVR(kernel="linear", C=1000)

#regressor = SVR(kernel="rbf", C=0.1)
#regressor = SVR(kernel="rbf", C=1)
#regressor = SVR(kernel="rbf", C=10)
#regressor = SVR(kernel="rbf", C=100)
#regressor = SVR(kernel="rbf", C=1000)

#regressor = SVR(kernel="poly", degree=1, C=0.1)
#regressor = SVR(kernel="poly", degree=2, C=0.1)
regressor = SVR(kernel="poly", degree=3, C=1000)

# Initialize scaler
scaler = StandardScaler()

# Fit on training data and transform
X_train_scaled = scaler.fit_transform(X_train)

# Transform test data using the same scaler
X_test_scaled = scaler.transform(X_test)

regressor.fit(X_train_scaled, Y_train)

Y_train_pred = regressor.predict(X_train_scaled)

from sklearn.metrics import r2_score # for r2 score evaluvation importing the function from metrics library

r_score_train = r2_score(Y_train,Y_train_pred) # comparing the predicted values and test(Actual) values to calculate R2Score 
print("training r2",r_score_train)

Y_pred = regressor.predict(X_test_scaled)

from sklearn.metrics import r2_score # for r2 score evaluvation importing the function from metrics library

r_score= r2_score(Y_test,Y_pred) # comparing the predicted values and test(Actual) values to calculate R2Score 
print("test r2",r_score)

training r2 0.8073572554875614
test r2 0.856648767594656

C:\Users\z030703\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [96]:
import pickle

# Save both model and scaler
pickle.dump((regressor, scaler), open("Insurance_premium_predictor_SVR.sav", "wb"))

# Load both
loaded_model, loaded_scaler = pickle.load(open("Insurance_premium_predictor_SVR.sav", "rb"))

# Scale new input before prediction
new_input = [[45,0,27.9,0,0]]
new_input_scaled = loaded_scaler.transform(new_input)

result = loaded_model.predict(new_input_scaled)
print(result)

[7758.26928856]

C:\Users\z030703\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(